--- 
- hosts: all
  become: true

  vars_files:
    - vars.yml
    - vault.yml

  tasks:
    - name: Install Pip.
      apt: name=python3-pip state=present

    - name: Install Python requirements.
      pip: 
        name: "{{ python_requirements }}"
        state: present

    - name: Enusre base Docker paths exsits
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ docker_base_dir }}"

    - name: Ensure networks exist
      docker_network:
        name: "{{ runner_docker_network }}"
          
    - name: Ensure paths exist 
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ runner_volumes }}"

    - name: Ensure Gitlab Runner container is started and running
      docker_container:
        name: "{{ runner_container_name }}"
        image: "{{ runner_image }}"
        user: "root:root"
        networks:
          - name: "{{ runner_docker_network }}"
        volumes: "{{ runner_volumes }}"
        state: started 
        restart: yes


    - name: Run Docker Gitlab Runner registration
      community.docker.docker_container_exec:
        container: "{{ runner_container_name }}"
        command: "{{ register_command }}"
      register: result

    - name: Print stderr lines
      debug:
        var: result.stderr_lines


    # Module meant for runners installed directly on host
    #- name: Register Gitlab Runner
      #community.general.gitlab_runner:
        #api_url: https://gitlab.com/
        #api_token: "{{ runner_access_token }}"
        #registration_token: "{{ runner_registration_token }}" 
        #description: Docker Machine t1
        #state: present
        #active: True
        #tag_list: ['docker']
        #run_untagged: False
        #locked: False
 
 
 
